// apps/solid-js/src/App.jsx
import { Switch, Match } from "solid-js";
import { currentPath } from "./router";
import Login from "./routes/Login";
import Callback from "./routes/Callback";
import Home from "./routes/Home";

export default function App() {
  return (
    <main class="app">
      <Switch>
        <Match when={currentPath() === "/home"}>
          <Home />
        </Match>
        <Match when={currentPath() === "/callback"}>
          <Callback />
        </Match>
        <Match when={true}>
          <Login />
        </Match>
      </Switch>
    </main>
  );
}

// apps/svelte-ts/src/App.svelte
<script lang="ts">
  import { currentPath } from './router';
  import Login from './routes/Login.svelte';
  import Callback from './routes/Callback.svelte';
  import Home from './routes/Home.svelte';
</script>

<main class="app">
  {#if $currentPath === '/home'}
    <Home />
  {:else if $currentPath === '/callback'}
    <Callback />
  {:else}
    <Login />
  {/if}
</main>
