// apps/vue-ts/src/pages/Callback.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();

onMounted(() => {
  // main.js already processes callback before mount
  router.replace("/");
});
</script>

<template>
  <section class="card">
    <div class="title">Signing you in…</div>
    <div class="sub">Handling Auth0 callback</div>
    <div class="small">If you see this, reload once.</div>
  </section>
</template>

// apps/react-js/src/pages/Callback.jsx
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { auth } from "../auth";

export default function Callback() {
  const nav = useNavigate();
  const [msg, setMsg] = useState("Signing you in…");

  useEffect(() => {
    (async () => {
      try {
        await auth.handleRedirectCallback();
        nav("/home", { replace: true });
      } catch (e) {
        setMsg("Login callback failed. Check Auth0 callback URL and env vars.");
        console.error(e);
      }
    })();
  }, [nav]);

  return (
    <section className="card">
      <div className="title">{msg}</div>
      <div className="sub">Handling Auth0 callback</div>
    </section>
  );
}
