// apps/react-js/src/App.jsx
import React from "react";
import { Route, Routes } from "react-router-dom";
import Login from "./pages/Login";
import Callback from "./pages/Callback";
import Home from "./pages/Home";

export default function App() {
  return (
    <Routes>
      <Route path="/" element={<Login />} />
      <Route path="/callback" element={<Callback />} />
      <Route path="/home" element={<Home />} />
    </Routes>
  );
}

// apps/svelte-js/src/App.svelte
<!-- apps/svelte-js/src/App.svelte -->
<script>
  import { route } from "./router";
  import Login from "./routes/Login.svelte";
  import Callback from "./routes/Callback.svelte";
  import Home from "./routes/Home.svelte";
</script>

<main class="app">
  {#if $route === "/callback"}
    <Callback />
  {:else if $route === "/home"}
    <Home />
  {:else}
    <Login />
  {/if}
</main>
