// apps/react-ts/src/App.tsx
import React from "react";
import { Route, Routes, useLocation } from "react-router-dom";
import Login from "./pages/Login";
import Callback from "./pages/Callback";
import Home from "./pages/Home";

export default function App() {
  const loc = useLocation();
  const sizeClass = loc.pathname.startsWith("/home") ? "md" : "sm";

  return (
    <main className="app">
      <section className={`card ${sizeClass}`}>
        <Routes>
          <Route path="/" element={<Login />} />
          <Route path="/callback" element={<Callback />} />
          <Route path="/home" element={<Home />} />
        </Routes>
      </section>
    </main>
  );
}

// apps/svelte-js/src/App.svelte
<!-- apps/svelte-js/src/App.svelte -->
<script>
  import { route } from "./router";
  import Login from "./routes/Login.svelte";
  import Callback from "./routes/Callback.svelte";
  import Home from "./routes/Home.svelte";
</script>

<main class="app">
  {#if $route === "/callback"}
    <Callback />
  {:else if $route === "/home"}
    <Home />
  {:else}
    <Login />
  {/if}
</main>
