// apps/react-js/src/pages/Callback.jsx
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { auth } from "../auth";

export default function Callback() {
  const nav = useNavigate();
  const [msg, setMsg] = useState("Signing you in…");

  useEffect(() => {
    (async () => {
      try {
        await auth.handleRedirectCallback();
        nav("/home", { replace: true });
      } catch (e) {
        setMsg("Login callback failed. Check Auth0 callback URL and env vars.");
        console.error(e);
      }
    })();
  }, [nav]);

  return (
    <section className="card">
      <div className="title">{msg}</div>
      <div className="sub">Handling Auth0 callback</div>
    </section>
  );
}

// apps/vue-js/src/pages/Callback.vue
<script setup>
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { auth } from "../auth";

const router = useRouter();
const errorMsg = ref("");

onMounted(async () => {
  try {
    await auth.handleRedirectCallback();
    router.replace("/home");
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    errorMsg.value = msg || "Login callback failed.";
  }
});
</script>

<template>
  <section class="card">
    <div class="title">Signing you in…</div>
    <div class="sub">Handling Auth0 callback</div>

    <div v-if="errorMsg" class="status err" style="margin-top:14px;">
      <span>Error: {{ errorMsg }}</span>
      <router-link class="link" to="/">Back to Login</router-link>
    </div>
  </section>
</template>
