// apps/vue-js/src/pages/Callback.vue
<script setup>
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { auth } from "../auth";

const router = useRouter();
const errorMsg = ref("");

onMounted(async () => {
  try {
    await auth.handleRedirectCallback();
    router.replace("/home");
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    errorMsg.value = msg || "Login callback failed.";
  }
});
</script>

<template>
  <section class="card">
    <div class="title">Signing you in…</div>
    <div class="sub">Handling Auth0 callback</div>

    <div v-if="errorMsg" class="status err" style="margin-top:14px;">
      <span>Error: {{ errorMsg }}</span>
      <router-link class="link" to="/">Back to Login</router-link>
    </div>
  </section>
</template>

// apps/react-ts/src/pages/Callback.tsx
import React, { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { auth } from "../auth";

export default function Callback() {
  const nav = useNavigate();
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      try {
        await auth.handleRedirectCallback();
        nav("/home", { replace: true });
      } catch (e: any) {
          const message =
            e?.error === "access_denied" ? "Login cancelled." : "Login callback failed.";
          sessionStorage.setItem("stackauth_notice", message);
          nav("/", { replace: true });
        }
    })();
  }, [nav]);

  return (
    <div>
      <div className="title h1">Signing you in…</div>
      <div className="sub">Handling Auth0 callback</div>

      {error && (
        <div className="row">
          <div className="err">Error: {error}</div>
          <Link className="a" to="/">Back to Login</Link>
        </div>
      )}
    </div>
  );
}
